### ISSUE TITLE
POPUP issues

### ISSUE THREAD

**Issue by jerymey** [binyamolango/Personal-Portfolio#18]

**Comment by jerymey** [comment]
**These are the main issues that are listed on your Pull request:**

- [ ]  In order to have DRY code kindly consider not having different js files for each pop-up by using a single function to map into your projects arrays and create each pop-up as their structures are the same use a single function to iterate over your array and that will make your codebase professional check below all the number of the js files you have which are doing the same work and fix all of them into one.
- [ ] kindly consider linking all your HTML files into one cause currently your pop-ups are being opened in a new tab which is not giving a good user experience

**Comment by binyamolango** [comment]
@jerymey Great. I will try to address the issue. Thank you!
